# Generated by Django 3.2.7 on 2021-10-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211001_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codregister',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
